@startuml CalculatorApp
class CalculatorApp

class Calculator {
  -instance: CalculatorSingleton
  +getInstance(): CalculatorSingleton
}

interface Operation {
  +Operation(num1: double, num2: double): double
}

class Plus {
  +Operation(num1: double, num2: double): double
  void methods()
}

class Minus {
  +Operation(num1: double, num2: double): double
  void methods()
}

class Multiplication {
  +Operation(num1: double, num2: double): double
  void methods()
}

class Split {
  +Operation(num1: double, num2: double): double
  void methods()
}

CalculatorApp --> CalculatorSingleton
CalculatorSingleton --> Operation
Plus --|> Operation
Minus --|> Operation
Multiplication --|> Operation
Split --|> Operation

@enduml